name: First
on: workflow_dispatch
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: first
        run: echo First1
      - name: second
        run: |
          echo Second1
          echo Second2
