name: Python_file
on: push
jobs:
  strat_project:
    runs-on: ubuntu-latest
    steps:
      - name: Download code
        uses: actions/checkout@v4
      - name: Get Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' 
      - name: Run code
        run: python base.py
      
      
