name: test
on: push

jobs:
 m_test:
   runs-on: ubuntu-latest
   steps:
     - name: Download code
       uses: actions/checkout@v4
     - name: Get python
       uses: actions/setup-python@v5
       with:
         python-version: '3.10'
         cache: 'pip' # caching pip dependencies

     - run: pip install -r requirements.txt
     - name: run code
       run: python mt.py

 m1_test:
   needs: m_test
   runs-on: ubuntu-latest
   steps:
     - name: Download code
       uses: actions/checkout@v4
     - run: pip install -r requirements.txt
     - name: run code
       run: python mt.py

     - name: Display structure of downloaded files
       run: ls -l
       run: pwd
     - name: Download a single artifact
       uses: actions/download-artifact@v4
       with:
        name: test.out
